version: 0.2.{build}-{branch}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
branches:
  # blacklist
  except:
    - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release
before_build:
  appveyor-retry nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}-{branch}.{platform}'
  assembly_file_version: '{version}.{platform}'
  assembly_informational_version: '{version}-{branch}.{platform}'
build:
  publish_wap: false
  parallel: true
  verbosity: minimal
artifacts:
  - path: BlogEdit\bin\$(platform)\$(configuration)\BlogEdit.exe