version: 0.2.{build}-{branch}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
  - AnyCPU
#  - x64
branches:
  # blacklist
  except:
    - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: AnyCPU
      configuration: Release
#    - platform: x64
#      configuration: Release
before_build:
  appveyor-retry nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: normal
artifacts:
  - path: BlogEdit\bin\$(platform)\$(configuration)\
#    name: BlogEdit_$(platform)
    name: BlogEdit_$(build)($(branch))
