version: 0.1
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
  - Any CPU
branches:
  # blacklist
  except:
    - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release
    - platform: Any CPU
      configuration: Release
init:
- cmd: "set appVeyorBuildVersion=%appveyor_build_version%\necho appVeyorBuildVersion:%appVeyorBuildVersion% \n\nset branch=%APPVEYOR_REPO_BRANCH%\necho branch:%branch%\n\nset gitVersion=%branch:~-3%\necho gitversion:%gitVersion%\n\nset newVersion=%appveyor_build_version%.%gitVersion%.%APPVEYOR_BUILD_NUMBER%\necho %newVersion%\n\n"
- cmd: appveyor UpdateBuild -Version "%newVersion%"
#before_build:
#  appveyor-retry nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: "echo Building version:%appveyor_build_version%"
- cmd: "nuget restore\nmsbuild JokerBlogEdit.sln /t:build /p:Configuration=Release"
build:
  publish_wap: false
  parallel: true
  verbosity: minimal