version: 0.1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
branches:
  # blacklist
  except:
    - gh-pages
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release
# exclude configuration from the matrix. Works similarly to 'allow_failures' but build not even being started for excluded combination.
  exclude:
    - platform: x86
      configuration: Debug
before_build:
  appveyor-retry nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "0.1.{build}"
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_wap: false
  parallel: true
  verbosity: normal